In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('/Users/shivendragupta/Desktop/NLP/IMDB Dataset 2.csv')

In [8]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

# Lower Casing 

In [11]:
df['review'][6].lower()

"i sure would like to see a resurrection of a up dated seahunt series with the tech they have today it would bring back the kid excitement in me.i grew up on black and white tv and seahunt with gunsmoke were my hero's every week.you have my vote for a comeback of a new sea hunt.we need a change of pace in tv and this would work for a world of under water adventure.oh by the way thank you for an outlet like this to view many viewpoints about tv and the many movies.so any ole way i believe i've got what i wanna say.would be nice to read some more plus points about sea hunt.if my rhymes would be 10 lines would you let me submit,or leave me out to be in doubt and have me to quit,if this is so then i must go so lets do it."

In [12]:
df['review'] = df['review'].str.lower()

In [13]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# Removing HTML tags

In [14]:
import re

In [15]:
def removeHtmlTags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [16]:
df['review'] = df['review'].apply(removeHtmlTags)

In [17]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# Remove URLS

In [18]:
def remove_url(text):
    pattern = re.compile(r'https:?//\S+|www\.\S+') 
    return pattern.sub(r'',text)

In [21]:
text1 = "check out my link https://www.google.com"

In [22]:
remove_url(text1)

'check out my link '

# Remove punctuations

In [23]:
import string

In [24]:
exclude = string.punctuation

In [25]:
def removePunc(text):
    for i in exclude:
        text = text.replace(i,'')
    return text

In [26]:
df['review'] = df['review'].apply(removePunc)

In [27]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [28]:
def removePuncFaster(text):
    return text.translate(str.maketrans('','',exclude))

In [29]:
df['review'] = df['review'].apply(removePuncFaster)

# Chat Word Treatment


In [31]:
slangs = {
  "AFAIK": "As Far As I Know",
  "AFK": "Away From Keyboard",
  "ASAP": "As Soon As Possible",
  "ATK": "At The Keyboard",
  "ATM": "At The Moment",
  "A3": "Anytime, Anywhere, Anyplace",
  "BAK": "Back At Keyboard",
  "BBL": "Be Back Later",
  "BBS": "Be Back Soon",
  "BFN": "Bye For Now",
  "B4N": "Bye For Now",
  "BRB": "Be Right Back",
  "BRT": "Be Right There",
  "BTW": "By The Way",
  "B4": "Before",
  "CU": "See You",
  "CUL8R": "See You Later",
  "CYA": "See You",
  "FAQ": "Frequently Asked Questions",
  "FC": "Fingers Crossed",
  "FWIW": "For What It's Worth",
  "FYI": "For Your Information",
  "GAL": "Get A Life",
  "GG": "Good Game",
  "GN": "Good Night",
  "GMTA": "Great Minds Think Alike",
  "GR8": "Great!",
  "G9": "Genius",
  "IC": "I See",
  "ICQ": "I Seek You",
  "ILU": "I Love You",
  "IMHO": "In My Honest/Humble Opinion",
  "IMO": "In My Opinion",
  "IOW": "In Other Words",
  "IRL": "In Real Life",
  "KISS": "Keep It Simple, Stupid",
  "LDR": "Long Distance Relationship",
  "LMAO": "Laugh My A** Off",
  "LOL": "Laughing Out Loud",
  "LTNS": "Long Time No See",
  "L8R": "Later",
  "MTE": "My Thoughts Exactly",
  "M8": "Mate",
  "NRN": "No Reply Necessary",
  "OIC": "Oh I See",
  "PITA": "Pain In The A**",
  "PRT": "Party",
  "PRW": "Parents Are Watching",
  "QPSA?": "Que Pasa?",
  "ROFL": "Rolling On The Floor Laughing",
  "ROFLOL": "Rolling On The Floor Laughing Out Loud",
  "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
  "SK8": "Skate",
  "STATS": "Your sex and age",
  "ASL": "Age, Sex, Location",
  "THX": "Thank You",
  "TTFN": "Ta-Ta For Now!",
  "TTYL": "Talk To You Later",
  "U": "You",
  "U2": "You Too",
  "U4E": "Yours For Ever",
  "WB": "Welcome Back",
  "WTF": "What The F***",
  "WTG": "Way To Go!",
  "WUF": "Where Are You From?",
  "W8": "Wait...",
  "7K": "Sick:-D Laugher",
  "TFW": "That feeling when",
  "MFW": "My face when",
  "MRW": "My reaction when",
  "IFYP": "I feel your pain",
  "TNTL": "Trying not to laugh",
  "JK": "Just kidding",
  "IDC": "I dont care",
  "ILY": "I love you",
  "IMU": "I miss you",
  "ADIH": "Another day in hell",
  "ZZZ": "Sleeping, bored, tired",
  "WYWH": "Wish you were here",
  "TIME": "Tears in my eyes",
  "BAE": "Before anyone else",
  "FIMH": "Forever in my heart",
  "BSAAW": "Big smile and a wink",
  "BWL": "Bursting with laughter",
  "BFF": "Best friends forever",
  "CSL": "Cant stop laughing"
}


In [37]:
def ChatWordTreatement(text):
    for key,value in slangs.items():
        text = text.replace(key,value)
    return text

In [40]:
text = 'MTE very nice'

In [41]:
ChatWordTreatement(text)

'My Thoughts Exactly very nice'

# Spelling correction

In [44]:
from textblob import TextBlob

In [61]:
text = "this line has sptlling mistakes"

In [62]:
txtblb = TextBlob(text)

In [64]:
txtblb.correct().string

'this line has spelling mistakes'

# Removing stop words

# a are the of my

In [69]:
from nltk.corpus import stopwords
import nltk

In [74]:
sw = stopwords.words('english')

In [86]:
def removeStopWords(text):
    new_text = []
    for word in text.split():
        if word in sw:
            new_text.append('')
        else:
            new_text.append(word)
    return " ".join(new_text)


In [87]:
text1 = 'my name is shivendra gupta'

In [88]:
removeStopWords(text1)

' name  shivendra gupta'

In [89]:
df['review'] = df['review'].apply(removeStopWords)

In [90]:
df.head()

review sentiment
0  one    reviewers  mentioned   watching  1 oz e...  positive
1   wonderful little production  filming techniqu...  positive
2   thought    wonderful way  spend time    hot s...  positive
3  basically theres  family   little boy jake thi...  negative
4  petter matteis love   time  money   visually s...  positive

In [93]:
import emoji

In [94]:
print(emoji.demojize("As Far As I Know 🤔"))

As Far As I Know :thinking_face:


In [ ]:
import re

def remove_emojis(text):
    emoji_pattern = re.compile("["
                                "\U0001F600-\U0001F64F"  # Emoticons
                                "\U0001F300-\U0001F5FF"  # Symbols & pictographs
                                "\U0001F680-\U0001F6FF"  # Transport & map symbols
                                "\U0001F1E0-\U0001F1FF"  # Flags (iOS)
                                "\U00002702-\U000027B0"  # Dingbats
                                "\U000024C2-\U0001F251"  # Enclosed characters
                                "]+", flags=re.UNICODE)
    
    return emoji_pattern.sub(r'', text)

text_with_emojis = "Hello 😂, I love Python 🐍! How are you? 😊"

In [96]:
remove_emojis(text_with_emojis)

'Hello , I love Python ! How are you? '

# Tokenization

In [100]:
text = "I have a M.S degree in A.I!"

In [101]:
text.split()

['I', 'have', 'a', 'M.S', 'degree', 'in', 'A.I!']

In [102]:
nltk.word_tokenize(text)

['I', 'have', 'a', 'M.S', 'degree', 'in', 'A.I', '!']

In [104]:
import spacy

In [ ]:
nlp = spacy.load('en_core_web_sm')

SyntaxError: invalid syntax (581980377.py, line 1)

In [ ]:
doc1 = nlp(text)

In [ ]:
for token in doc1:
    print(token)

# Stemming

In [107]:
from nltk.stem.porter import PorterStemmer

In [108]:
ps = PorterStemmer()

In [122]:
def stem(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [123]:
text = 'walking the walked walk'

In [124]:
stem(text)

'walk the walk walk'

In [125]:
text1 = "probably the alltime"

In [126]:
stem(text1)

'probabl the alltim'

In [127]:
from nltk.stem import WordNetLemmatizer

In [128]:
word_net_lemma = WordNetLemmatizer()

In [129]:
text = "He was running and eating at the same time.He has bad habit of swimming afte playing long hours in the sun."


In [130]:
for word in text:
    for i in exclude:
        word.replace(i,'')

In [134]:
for word in text.split():
    print(word_net_lemma.lemmatize(word,pos='v'))

He
be
run
and
eat
at
the
same
time.He
have
bad
habit
of
swim
afte
play
long
hours
in
the
sun.


# Bag of Word

In [146]:
from sklearn.feature_extraction.text import CountVectorizer

In [147]:
cv = CountVectorizer()

In [148]:
bow = cv.fit_transform(df['review'])

In [149]:
cv.vocabulary_

{'one': 139493,
 'reviewers': 163208,
 'mentioned': 123484,
 'watching': 212112,
 'oz': 143239,
 'episode': 64541,
 'youll': 220085,
 'hooked': 93682,
 'right': 163980,
 'exactly': 66499,
 'happened': 87829,
 'methe': 124089,
 'first': 73580,
 'thing': 195593,
 'struck': 187144,
 'brutality': 29026,
 'unflinching': 205255,
 'scenes': 169441,
 'violence': 209793,
 'set': 173770,
 'word': 217165,
 'go': 82283,
 'trust': 202166,
 'show': 176147,
 'faint': 69036,
 'hearted': 89458,
 'timid': 198062,
 'pulls': 155907,
 'punches': 155990,
 'regards': 160605,
 'drugs': 58777,
 'sex': 174036,
 'hardcore': 88126,
 'classic': 38397,
 'use': 207262,
 'wordit': 217184,
 'called': 31237,
 'nickname': 134175,
 'given': 81823,
 'oswald': 141361,
 'maximum': 121508,
 'security': 171641,
 'state': 184726,
 'penitentary': 146129,
 'focuses': 74986,
 'mainly': 118473,
 'emerald': 62419,
 'city': 38093,
 'experimental': 67616,
 'section': 171606,
 'prison': 153800,
 'cells': 34270,
 'glass': 81949,
 'fron

In [150]:
bow[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [151]:
bow.shape

(50000, 221399)

In [152]:
print(bow)

  (0, 139493)	1
  (0, 163208)	1
  (0, 123484)	1
  (0, 212112)	2
  (0, 143239)	5
  (0, 64541)	2
  (0, 220085)	1
  (0, 93682)	1
  (0, 163980)	2
  (0, 66499)	1
  (0, 87829)	1
  (0, 124089)	1
  (0, 73580)	2
  (0, 195593)	1
  (0, 187144)	2
  (0, 29026)	1
  (0, 205255)	1
  (0, 169441)	1
  (0, 209793)	4
  (0, 173770)	1
  (0, 217165)	1
  (0, 82283)	1
  (0, 202166)	1
  (0, 176147)	3
  (0, 69036)	1
  :	:
  (49999, 111997)	1
  (49999, 100368)	1
  (49999, 67387)	1
  (49999, 17144)	1
  (49999, 88193)	1
  (49999, 133136)	1
  (49999, 98234)	1
  (49999, 97612)	1
  (49999, 69619)	1
  (49999, 14912)	1
  (49999, 201241)	1
  (49999, 108049)	1
  (49999, 183119)	1
  (49999, 121817)	1
  (49999, 161739)	1
  (49999, 64582)	1
  (49999, 30862)	1
  (49999, 134546)	1
  (49999, 35067)	1
  (49999, 67472)	1
  (49999, 83313)	1
  (49999, 161706)	1
  (49999, 130505)	1
  (49999, 46413)	1
  (49999, 219952)	1


# bi gram

In [153]:
cv2 = CountVectorizer(ngram_range=(2,2))

In [156]:
bow2 = cv2.fit_transform(df['review'])

In [157]:
cv2.vocabulary_

{'one reviewers': 2056050,
 'reviewers mentioned': 2421796,
 'mentioned watching': 1839678,
 'watching oz': 3173830,
 'oz episode': 2095294,
 'episode youll': 925620,
 'youll hooked': 3300267,
 'hooked right': 1388879,
 'right exactly': 2432600,
 'exactly happened': 964225,
 'happened methe': 1313963,
 'methe first': 1846570,
 'first thing': 1103451,
 'thing struck': 2925762,
 'struck oz': 2800962,
 'oz brutality': 2095260,
 'brutality unflinching': 387318,
 'unflinching scenes': 3066968,
 'scenes violence': 2513007,
 'violence set': 3132089,
 'set right': 2586039,
 'right word': 2434188,
 'word go': 3251038,
 'go trust': 1235355,
 'trust show': 3026202,
 'show faint': 2623062,
 'faint hearted': 1010768,
 'hearted timid': 1338634,
 'timid show': 2967111,
 'show pulls': 2624535,
 'pulls punches': 2295504,
 'punches regards': 2296468,
 'regards drugs': 2373981,
 'drugs sex': 838621,
 'sex violence': 2592751,
 'violence hardcore': 3131658,
 'hardcore classic': 1319585,
 'classic use': 523

In [159]:
bow2[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

# if we use (1,2)
both bi gram and unigram
# id we use (1,3)
we use all unigram bigram trigram

# tfIDF

In [160]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [161]:
tfid = TfidfVectorizer()

In [162]:
tf = tfid.fit_transform(df['review'])

In [163]:
tfid.vocabulary_

{'one': 139493,
 'reviewers': 163208,
 'mentioned': 123484,
 'watching': 212112,
 'oz': 143239,
 'episode': 64541,
 'youll': 220085,
 'hooked': 93682,
 'right': 163980,
 'exactly': 66499,
 'happened': 87829,
 'methe': 124089,
 'first': 73580,
 'thing': 195593,
 'struck': 187144,
 'brutality': 29026,
 'unflinching': 205255,
 'scenes': 169441,
 'violence': 209793,
 'set': 173770,
 'word': 217165,
 'go': 82283,
 'trust': 202166,
 'show': 176147,
 'faint': 69036,
 'hearted': 89458,
 'timid': 198062,
 'pulls': 155907,
 'punches': 155990,
 'regards': 160605,
 'drugs': 58777,
 'sex': 174036,
 'hardcore': 88126,
 'classic': 38397,
 'use': 207262,
 'wordit': 217184,
 'called': 31237,
 'nickname': 134175,
 'given': 81823,
 'oswald': 141361,
 'maximum': 121508,
 'security': 171641,
 'state': 184726,
 'penitentary': 146129,
 'focuses': 74986,
 'mainly': 118473,
 'emerald': 62419,
 'city': 38093,
 'experimental': 67616,
 'section': 171606,
 'prison': 153800,
 'cells': 34270,
 'glass': 81949,
 'fron

In [165]:
tf[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])